"""Python wrappers for the original NicheDE R package."""

from nichedepy.api import (
    NicheDEResult,
    calculate_effective_niche,
    calculate_effective_niche_large_scale,
    call_nichede_function,
    celltype_level,
    celltype_level_fisher,
    check_colloc,
    contrast_post,
    create_library_matrix,
    create_niche_de_object,
    filter_nde,
    gene_level,
    gene_level_fisher,
    get_niche_de_genes,
    get_niche_de_pval_fisher,
    get_niche_de_pval_raw,
    merge_objects,
    nb_lik,
    niche_de_markers,
    niche_de_no_parallel,
    niche_lr_cell,
    niche_lr_spot,
    run_niche_de,
    run_pipeline,
    t_to_p,
    ultosymmetric,
)
from nichedepy.config import NicheDEConfig
from nichedepy.io import write_nichede_inputs

__all__ = [
    "NicheDEConfig",
    "NicheDEResult",
    "write_nichede_inputs",
    "create_library_matrix",
    "create_niche_de_object",
    "calculate_effective_niche",
    "calculate_effective_niche_large_scale",
    "run_niche_de",
    "niche_de_no_parallel",
    "niche_de_markers",
    "get_niche_de_genes",
    "get_niche_de_pval_raw",
    "get_niche_de_pval_fisher",
    "filter_nde",
    "merge_objects",
    "niche_lr_cell",
    "niche_lr_spot",
    "celltype_level",
    "celltype_level_fisher",
    "gene_level",
    "gene_level_fisher",
    "check_colloc",
    "contrast_post",
    "nb_lik",
    "t_to_p",
    "ultosymmetric",
    "call_nichede_function",
    "run_pipeline",
]
